### ISSUE TITLE
MaxRAMFraction "will be Deprecated in JDK10" when JDK 11 is given

### ISSUE THREAD

**Issue by edumucelli** [chriswhocodes/JaCoLine#1]
Great tool! I gave the following command line using the JDK 11 inspector:

```
java \
    -Dfile.encoding=UTF-8 \
    -Duser.timezone=GMT \
    -XX:+UseContainerSupport \
    -XX:MaxRAMFraction=2 \
    -XX:+UseG1GC \
    -XX:MaxGCPauseMillis=10 \
    -jar \
    /app.jar
```
Expected output for MaxRAMFraction:

`This switch was removed after JDK10. Your analysis was for JDK11`

But I had 

`This switch will be removed in the future. It will be Deprecated in JDK10.`

**Comment by chriswhocodes** [comment]
Hi @edumucelli 
According to the latest (JDK14) sources:
```
jdk14/src/hotspot/share/runtime/arguments.cpp:  { "MaxRAMFraction",               JDK_Version::jdk(10),  JDK_Version::undefined(), JDK_Version::undefined() },
jdk14/src/hotspot/share/runtime/arguments.cpp:  { "DefaultMaxRAMFraction",        JDK_Version::jdk(8),  JDK_Version::undefined(), JDK_Version::undefined() },
```
The first column is the "deprecated" version, the second is "obsoleted" and the third is "expired" (see the table at the bottom of https://chriswhocodes.com/hotspot_option_differences.html).

DefaultMaxRAMFraction was deprecated in JDK as it was being renamed to MaxRamFraction.

MaxRAMFraction was deprecated in JDK10.

Neither of them has been assigned a version where they will be obsoleted or expired yet so they can still be used in the JVM.

Here is the output from JDK14 for MaxRAMFraction:
```
chris@opencl:~/Downloads/jdk14-chriswhocodes-nightly-linux-x86_64-fastdebug$ ./bin/java -XX:MaxRAMFraction=2 -version
OpenJDK 64-Bit Server VM warning: Option MaxRAMFraction was deprecated in version 10.0 and will likely be removed in a future release.
openjdk version "14-internal" 2020-03-17
OpenJDK Runtime Environment nightly (fastdebug build 14-internal+0-adhoc.chris.jdk14)
OpenJDK 64-Bit Server VM nightly (fastdebug build 14-internal+0-adhoc.chris.jdk14, mixed mode, sharing)
```

**Comment by edumucelli** [comment]
@chriswhocodes thanks for the complementary information. Cheers!

**Comment by ilatypov** [comment]
Not sure why the issue was closed.  (The purpose of issue tracking is register us humans' concerns rather than defend the existing behaviour or documentation of software).

I found this issue via an online search, and a comment by François Marot in Carlos Sanchez's blog showed a forward-compatible option MaxRAMPercentage,

https://blog.csanchez.org/2018/06/21/running-a-jvm-in-a-container-without-getting-killed-ii/
