### ISSUE TITLE
Jacoline analysis suggests Missing +/- or = setting

### ISSUE THREAD

**Issue by vivdesh** [chriswhocodes/JaCoLine#12]
JVM suggests Missing +/- or = setting if that setting is needed and missing.
e.g.
% java -Xmx4g -Xmn3g -XX:UseG1GC -XX:+PrintFlagsFinal -version
Missing +/- setting for VM option 'UseG1GC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

%java -XX:UseAVX3  -version
Unrecognized VM option 'UseAVX3'
Did you mean 'UseAVX=<value>'? Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by chriswhocodes** [comment]
Thanks for the bug report.
With -XXUseG1GC the parser gets confused and assumes that the digit is the start of the parameter value.
```
Request has 1 parts
part after prefix:UseG1GC
Creating KeyValue (-XX:,UseG,1GC)
Parsed: -XX:UseG=1GC
UseG not found in JDK8
Found UseG in earliest null
findClosestWord to UseG
Closest word to UseG is UseZGC
type: value:1GC
```

I'll add a regression test for this and then fix the parser.

**Comment by chriswhocodes** [comment]
Fixed with https://github.com/chriswhocodes/JaCoLine/commit/69907de5ff0aa7b368dbd2e939100e5767b4b325
