### ISSUE TITLE
Local instantiation of Jacoline

### ISSUE THREAD

**Issue by vivdesh** [chriswhocodes/JaCoLine#14]
Is it possible to locally deploy the service? if yes, would you please share the steps?

**Comment by chriswhocodes** [comment]
Hi @vivdesh yes anyone can run a local instance of JaCoLine.

You will need a local copy of https://github.com/chriswhocodes/VMOptionsExplorer plus the JDK repositories from OpenJDK mercurial that you wish JaCoLine to support.

Execute VMOptionsExplorer against those JDKs (you may need to edit some paths in the source code) and this will produce a directory called "serialised" which contains the VM switch data needed by JaCoLine.

You will also need to provide JaCoLine with a file containing a ban-list of words (needed to prevent XSS attacks etc if you are running a public instance). If you are running locally then this file can be empty.

Kind regards,

Chris

**Comment by vivdesh** [comment]
Thank you, for your help. :)
