### ISSUE TITLE
G1RSetUpdatingPauseTimePercent is rejected as bad input

### ISSUE THREAD

**Issue by thedoc31** [chriswhocodes/JaCoLine#27]
When attempting to validate a commandline with the "G1RSetUpdatingPauseTimePercent" option, [JaCoLine](https://jacoline.dev/inspect) is reporting the option as bad input. 
Example:

`
/usr/bin/java ‑Dfoo=bar ‑cp=/all/the/jars ‑java.library.path=/home/chris/lib ‑XX:+UseG1GC ‑XX:MaxGCPauseMillis=500 ‑XX:InitiatingHeapOccupancyPercent=70  ‑XX:G1HeapRegionSize=8m -XX:G1RSetUpdatingPauseTimePercent=5
`
This is a valid option per https://docs.oracle.com/en/java/javase/11/gctuning/garbage-first-garbage-collector-tuning.html#GUID-90E30ACA-8040-432E-B3A0-1E0440AB556A and shouldn't be rejected.

**Comment by chriswhocodes** [comment]
Thanks for reporting. I confirm this is a bug. That switch is getting caught up in my antispam filter. Will fix.

**Comment by chriswhocodes** [comment]
This is now fixed and you can validate command lines containing that switch e.g. https://jacoline.dev/retrieve/9828
Thanks again for reporting :)
